import os
import sys
from dotenv import load_dotenv
from workflow import app_workflow

# Load environment variables
load_dotenv()

def main():
    # Verify API key
    if not os.getenv("GROQ_API_KEY"):
        print("❌ Error: GROQ_API_KEY environment variable is not set.")
        print("Please set it in your .env file or command prompt: set GROQ_API_KEY=gsk_...")
        sys.exit(1)

    url = "https://quotes.toscrape.com/"
    question = "Summarize the website and list the first 3 quotes with their authors."

    print(f"🚀 Initializing test run for URL: {url}")
    print(f"📝 Question: {question}")
    print("-" * 50)

    # Initial state inputs
    inputs = {
        "url": url,
        "question": question,
        "raw_html": None,
        "cleaned_text": None,
        "analysis_result": None,
        "error": None
    }

    try:
        # Stream workflow steps
        print("🔄 Running LangGraph workflow steps:")
        for output in app_workflow.stream(inputs):
            for node_name, state_update in output.items():
                if "error" in state_update and state_update["error"]:
                    print(f"❌ Failed at node '{node_name}': {state_update['error']}")
                    sys.exit(1)
                
                if node_name == "scrape":
                    print("  ✓ Scrape Node: Scraped HTML using Selenium.")
                elif node_name == "parse":
                    print(f"  ✓ Parse Node: Extracted {len(state_update.get('cleaned_text', ''))} characters of text.")
                elif node_name == "llm_analysis":
                    print("  ✓ LLM Analysis Node: Structured response generated by Llama 3.3 via Groq.")
                elif node_name == "output":
                    print("  ✓ Output Node: Finalized state.")
                    print("-" * 50)
                    print("📊 Extraction Result:\n")
                    print(state_update.get("analysis_result"))
                    print("-" * 50)
                    
    except Exception as e:
        print(f"❌ Workflow execution crashed: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
